services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro 

    environment:
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INIT_PASSWORD=${MONGO_INIT_PASSWORD}

    networks:
      - backend

    restart: always

networks:
    backend:
volumes:
  mongodata:    
